### ISSUE TITLE
Waterfall visuals no longer interactive

### ISSUE THREAD

**Issue by J-Griffington** [nishantjainuk/SimpleWaterfall-PowerBI#82]
Hi

I have a dashboard tab with multiple waterfalls on it.
Previously, if you clicked the bar on any one of them, it acted like a filter and the other waterfalls on the same tab would change 'on-the-fly'
Now the only way to get them to change is by using dropdown filters at the top of the page.
I haven't changed anything, these have previously worked fine for months but I noticed the problem about a month ago. This is also affecting someone else I know with an entirely separate dashboard/different data source, so I know that it's not an isolated issue (also note that others on the Power BI forum are experiencing similar)

Any ideas what's causing this/how to fix it? It was a really cool feature of the visual, so hoping that it hasn't gone away forever

Thanks

**Comment by VatsalStoic** [comment]
Facing exactly same issue. This should be resolved at the earliest.

**Comment by nishantjainuk** [comment]
@J-Griffington 

Please see my comment [here ](https://github.com/nishantjainuk/SimpleWaterfall-PowerBI/issues/75#issuecomment-991867927) about this issue

Thanks

**Comment by Billytoh** [comment]
Hello,

Has the filtering feature been solved? I just updated the latest version but seems like not working. 

Thanks

**Comment by nishantjainuk** [comment]
@Billytoh , can you check if the latest version has rolled out to your tenant?

I still can't see the latest version in my tenant.

![image](https://user-images.githubusercontent.com/24504997/151147825-f7ee17ee-0eab-40dc-a593-039709d3625f.png)

**Comment by nishantjainuk** [comment]
No response received after bug fix
